### PR TITLE
Fixes #1, extends wordslists

### LINKED ISSUE #1: enhance adjectives.js
In some cases it does not work properly.
so... add genders to the object.

> Du gschlampade Britschn, zwidae!
> Du gschlampade Britschn, zwida**n**e!

### PR DESCRIPTION
**Pull request by NewOutlaw**

### CODE REVIEW

File: src/components/RandomWords.jsx [hunk 1]
```diff
@@ -6,14 +6,21 @@ import Adjectives from '../data/adjectives';
...
+  var prefix = '';
+  if(adjEnding == 'a')
+    prefix = 'n';
+
+  console.log("prefix: " + prefix);
+
   switch (gender) {
     case 'mas':
-      return 'er';
+      return prefix + 'er';
```
Comment (WanielDeiss) [inline src/components/RandomWords.jsx]: use  string interpolation

\`${prefix}er\`

File: src/components/RandomWords.jsx [hunk 2]
```diff
@@ -6,14 +6,21 @@ import Adjectives from '../data/adjectives';
...
     case 'fem':
-      return 'e';
+      return prefix + 'e';
```
Comment (WanielDeiss) [inline src/components/RandomWords.jsx]: use  string interpolation

\`${prefix}e\`

File: src/components/RandomWords.jsx [hunk 3]
```diff
@@ -6,14 +6,21 @@ import Adjectives from '../data/adjectives';
...
     default:
-      return 's';
+      return prefix + 's';
```
Comment (WanielDeiss) [inline src/components/RandomWords.jsx]: use  string interpolation

\`${prefix}s\`

File: src/components/RandomWords.jsx [hunk 4]
```diff
@@ -6,14 +6,21 @@ import Adjectives from '../data/adjectives';
 import Nouns from '../data/nouns';
 
 const RandomNumber = num => Math.floor((Math.random() * Math.floor(num)));
-const GetGenderSuffix = gender => {
+const GetGenderSuffix = (gender, adjEnding) => {
+
+  var prefix = '';
```
Comment (WanielDeiss) [inline src/components/RandomWords.jsx]: replace var with let

**Comment by WanielDeiss** [comment]
des schmeckt ma scho eha
